### ISSUE TITLE
Voting section and profile picture on rant pages bounce around in slow browsers while scolling [WebApp]

### ISSUE THREAD

**Issue by xlf1024** [devRant/devRant#338]
This seems to be due to the re-positioning javascript not being executed often enough.

Possible fix: Use css `position:sticky` instead, at least in supporting browsers:

```css
@supports(position:sticky){
  .rant-avatar-scroll, .vote-scroll{
    position: sticky;
    top: 110px;
    padding-top: unset !important;
  }
}
```
*Tested in Firefox 58*

However, the `@supports`-query will miss most browsers that actually *do* support `position:sticky` as the latter has already been around for a while: [https://caniuse.com/#feat=css-sticky](https://caniuse.com/#feat=css-sticky)
In this case, "partial" support is actually sufficient, as it only differs from "full" when tables are involved.
